# v1.4 - это версия конфига, обновите, если на сервере используется старая версия

telegram:
  token: "BOT_TOKEN" # Возьмите его в BotFather
  chat-id: "@group_link" # Можно добавить бота в группу "@group_link" или писать лично в сообщения админу "123456"
  group-link: "group_link" # "group_link" - без @
  send-all-than-text: "true" # отправлять ли в чат текст "3x Изображение" или стикеры, аудио
  time-check: "5" # сколько секунд ожидать между проверками сообщений

message:
  telegram: "<{user}> " # отображение пользователей пишущих в группе {user} - никнейм зашедшего игрока
  tg-check: "[TG" # предотвращение петли, проверка: "не отправлено ли сообщение ботом?"
  server: "<{player}> {message}" # отображение игроков пишущих в майнкрафте
  # {player} - никнейм зашедшего игрока
  # {message} - сообщение пользователя