# v1.1 - это версия конфига, обновите, если на сервере используется старая версия

telegram:
  token: "BOT_TOKEN" # Возьмите его в BotFather
  chat-id: "CHAT_ID" # Можно добавить бота в группу "@group_link" или писать лично в сообщения админу "123456"
  send-all-than-text: "true" # отправлять ли в чат текст "3x Изображение" или стикеры, аудио

message:
  telegram: "[TG|{user}] {message}" # отображение пользователей пишущих в группе {user} - никнейм зашедшего игрока
  # {message} - сообщение пользователя
  server: "[MC|{player}] " # отображение игроков пишущих в майнкрафте {player} - никнейм зашедшего игрока